[package]
name = "canteen-impl"
version = "0.0.1"
authors = ["jeffdn@gmail.com"]

[dependencies]
postgres = { version = "0.11", features = ["chrono"] }
rustc-serialize = "0.3"
chrono = "0.2"
canteen = { version = "0.0.1", path = "../rust-canteen" }
